// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsimulate_hw.h"

extern XSimulate_hw_Config XSimulate_hw_ConfigTable[];

XSimulate_hw_Config *XSimulate_hw_LookupConfig(u16 DeviceId) {
	XSimulate_hw_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSIMULATE_HW_NUM_INSTANCES; Index++) {
		if (XSimulate_hw_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSimulate_hw_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSimulate_hw_Initialize(XSimulate_hw *InstancePtr, u16 DeviceId) {
	XSimulate_hw_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSimulate_hw_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSimulate_hw_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

